use crate::*;

pub fn add_checks() {
    // TODO: have two lists, one for servers and one for workstations

    modprobe::add_module_blacklisted_check_list!(
        // GrapheneOS:
        // https://github.com/GrapheneOS/infrastructure/blob/86e765944fc1a1b69e9ccf27de5c8693405fe46d/etc/modprobe.d/local.conf
        "snd_intel8x0",
        "sr_mod",
        "snd_intel8x0m",
        // https://github.com/Kicksecure/security-misc/blob/master/etc/modprobe.d/30_security-misc_blacklist.conf
        "cdrom",
        "amd76x_edac",
        "ath_pci",
        "evbug",
        "snd_aw2",
        "snd_pcsp",
        "usbkbd",
        "usbmouse",
    );

    // TODO: have two lists, one for servers and one for workstations
    modprobe::add_module_disabled_check_list!(
        // Ubuntu: either duplicates, or disabled
        // https://git.launchpad.net/ubuntu/+source/kmod/tree/debian/modprobe.d/blacklist.conf?h=ubuntu/disco

        // disabling prohibits kernel modules from starting
        // https://github.com/Kicksecure/security-misc/blob/master/etc/modprobe.d/30_security-misc_disable.conf
        "cfg80211",
        "intel_agp",
        "ip_tables",
        "mousedev",
        "psmouse",
        "tls",
        "virtio_balloon",
        "virtio_console",
        // Network protocols
        "af_802154",
        "appletalk",
        "dccp",
        "netrom",
        "rose",
        "n_hdlc",
        "ax25",
        // "brcm80211",
        "x25",
        "decnet",
        "econet",
        "ipx",
        "psnap",
        "p8023",
        "p8022",
        "eepro100",
        "eth1394",
        // Asynchronous Transfer Mode (ATM)
        "atm",
        "ueagle_atm",
        "usbatm",
        "xusbatm",
        "n_hdlc",
        // Controller Area Network (CAN) Protocol
        "c_can",
        "c_can_pci",
        "c_can_platform",
        "can",
        "can_bcm",
        "can_dev",
        "can_gw",
        "can_isotp",
        "can_raw",
        "can_j1939",
        "can327",
        "ifi_canfd",
        "janz_ican3",
        "m_can",
        "m_can_pci",
        "m_can_platform",
        "phy_can_transceiver",
        "slcan",
        "ucan",
        "vxcan",
        "vcan",
        // Transparent Inter Process Communication (TIPC)
        "tipc",
        "tipc_diag",
        // Reliable Datagram Sockets (RDS)
        "rds",
        "rds_rdma",
        "rds_tcp",
        // Stream Control Transmission Protocol (SCTP)
        "sctp",
        "sctp_diag",
        "adfs",
        "affs",
        "bfs",
        "befs",
        "cramfs",
        "efs",
        "erofs",
        "exofs",
        "freevxfs",
        "f2fs",
        "hfs",
        "hfsplus",
        "squashfs",
        "hpfs",
        "jfs",
        "jffs2",
        "minix",
        "nilfs2",
        "ntfs",
        "omfs",
        "qnx4",
        "qnx6",
        "sysv",
        "ufs",
        "udf",
        "reiserfs",
        // Network File Systems
        "ksmbd",
        "gfs2",
        // Common Internet File System (CIFS)
        "cifs",
        "cifs_arc4",
        "cifs_md4",
        // Network File System (NFS)
        "nfs",
        "nfs_acl",
        "nfs_layout_nfsv41_files",
        "nfs_layout_flexfiles",
        "nfsd",
        "nfsv2",
        "nfsv3",
        "nfsv4",
        "usb_storage",
        "vivid",
        "floppy",
        "joydev",
        // bluetooth
        // disable Bluetooth to reduce attack surface due to extended history of
        // security vulnerabilities
        "bluetooth",
        "bluetooth_6lowpan",
        "bt3c_cs",
        "btbcm",
        "btintel",
        "btmrvl",
        "btmrvl_sdio",
        "btmtk",
        "btmtksdio",
        "btmtkuart",
        "btnxpuart",
        "btqca",
        "btrsi",
        "btrtl",
        "btsdio",
        "btusb",
        "virtio_bt",
        // firewire (IEEE 1394)
        "dv1394",
        "firewire_core",
        "firewire_ohci",
        "firewire_net",
        "firewire_sbp2",
        "ohci1394",
        "raw1394",
        "sbp2",
        "video1394",
        // GPS
        "garmin_gps",
        "gnss",
        "gnss_mtk",
        "gnss_serial",
        "gnss_sirf",
        "gnss_ubx",
        "gnss_usb",
        // Intel Management Engine (ME)
        // disabling may lead to breakages in numerous places without clear
        // debugging/error messages, may cause issues with firmware updates,
        // security, power management, display, and DRM.
        // "mei",
        // "mei_gsc",
        // "mei_gsc_proxy",
        // "mei_hdcp",
        // "mei_me",
        // "mei_phy",
        // "mei_pxp",
        // "mei_txe",
        // "mei_vsc",
        // "mei_vsc_hw",
        // "mei_wdt",
        // "microread_mei",

        // Intel Platform Monitoring Technology (PMT) Telemetry
        "pmt_class",
        "pmt_crashlog",
        "pmt_telemetry",
        // Thunderbolt
        "intel_wmi_thunderbolt",
        "thunderbolt",
        "thunderbolt_net",
        // Miscellaneous
        "hamradio",
        // "msr",

        // Framebuffer (fbdev)
        // video drivers are known to be buggy, cause kernel panics, and are
        // generally only used by legacy devices
        "aty128fb",
        "atyfb",
        "cirrusfb",
        "cyber2000fb",
        "cyblafb",
        "gx1fb",
        "hgafb",
        "i810fb",
        "intelfb",
        "kyrofb",
        "lxfb",
        "matroxfb_bases",
        "neofb",
        "nvidiafb",
        "pm2fb",
        "radeonfb",
        "rivafb",
        "s1d13xxxfb",
        "savagefb",
        "sisfb",
        "sstfb",
        "tdfxfb",
        "tridentfb",
        "vesafb",
        "vfb",
        "viafb",
        "vt8623fb",
        "udlfb",
        // replaced modules
        "asus_acpi",
        "bcm43xx",
        "de4x5",
        "prism54",
        // USB Video Device Class
        "uvcvideo",
        // Ubuntu
        "arkfb",
        "matroxfb_base",
        "mb862xxfb",
        "pm3fb",
        "s3fb",
        "snd_mixer_oss",
        "acquirewdt",
        "advantech_ec_wdt",
        "advantechwdt",
        "alim1535_wdt",
        "cadence_wdt",
        "cpu5wdt",
        "da9055_wdt",
        "da9063_wdt",
        "dw_wdt",
        "eurotechwdt",
        "f71808e_wdt",
        "i6300esb",
        "iTCO_wdt",
        "ibmasr",
        "it8712f_wdt",
        "kempld_wdt",
        "max63xx_wdt",
        "mena21_wdt",
        "menz69_wdt",
        "ni903x_wdt",
        "nv_tco",
        "pc87413_wdt",
        "pcwd_usb",
        "rave_sp_wdt",
        "sbc60xxwdt",
        "sbc_fitpc2_wdt",
        "sch311x_wdt",
        "smsc37b787_wdt",
        "sp5100_tco",
        "twl4030_wdt",
        "w83627hf_wdt",
        "w83977f_wdt",
        "wdat_wdt",
        "wm831x_wdt",
        "xen_wdt",
        "snd_pcm_oss",
        "alim7101_wdt",
        "da9052_wdt",
        "da9062_wdt",
        "ebc_c384_wdt",
        "exar_wdt",
        "hpwdt",
        "iTCO_vendor_support",
        "ib700wdt",
        "ie6xx_wdt",
        "it87_wdt",
        "machzwd",
        "mei_wdt",
        "menf21bmc_wdt",
        "mlx_wdt",
        "nic7018_wdt",
        "of_xilinx_wdt",
        "pcwd_pci",
        "pretimeout_panic",
        "retu_wdt",
        "sbc_epx_c3",
        "sc1200wdt",
        "simatic_ipc_wdt",
        "softdog",
        "tqmx86_wdt",
        "via_wdt",
        "w83877f_wdt",
        "wafer5823wdt",
        "wdt_pci",
        "wm8350_wdt",
        "ziirave_wdt",
        "pcspkr",
        "ac97",
        "ac97_codec",
        "ac97_plugin_ad1980",
        "ad1848",
        "ad1889",
        "adlib_card",
        "aedsp16",
        "ali5455",
        "btaudio",
        "cmpci",
        "cs4232",
        "cs4281",
        "cs461x",
        "cs46xx",
        "emu10k1",
        "es1370",
        "es1371",
        "esssolo1",
        "forte",
        "gus",
        "i810_audio",
        "kahlua",
        "mad16",
        "maestro",
        "maestro3",
        "maui",
        "mpu401",
        "nm256_audio",
        "opl3",
        "opl3sa",
        "opl3sa2",
        "pas2",
        "pss",
        "rme96xx",
        "sb",
        "sb_lib",
        "sgalaxy",
        "sonicvibes",
        "sound",
        "sscape",
        "trident",
        "trix",
        "uart401",
        "uart6850",
        "via82cxxx_audio",
        "v_midi",
        "wavefront",
        "ymfpci",
        "ac97_plugin_wm97xx",
        "ad1816",
        "audio",
        "awe_wave",
        "dmasound_core",
        "dmasound_pmac",
        "harmony",
        "sequencer",
        "soundcard",
        "usb_midi",
        "microcode",
    );
}
